fix: added ability to hash password
championswimmer/onepixel_backend pull request #18
Opened 2023-11-05 13:42 UTC by SanjaySinghRajpoot

Fixes #17

2023-11-10 08:59 UTC, championswimmer requested changes
Please add unit tests for hash and verify password

2023-11-18 12:42 UTC, SanjaySinghRajpoot commented
> Please add unit tests for hash and verify password

I have added them you can check now.

2023-11-21 07:42 UTC, championswimmer commented on src/controllers/users.go
> +	if err != nil {
this call should not fail (under any normal operation)
Can you do a `lo.Must` wrapper simply instead ?

2023-11-21 07:42 UTC, championswimmer requested changes

2023-11-21 07:42 UTC, championswimmer commented on src/utils/utils.go
> +		return "", fmt.Errorf("could not hash password %w", err)
this call should not fail (under any normal operation)
Can you do a `lo.Must` wrapper simply instead ?

2023-12-01 09:34 UTC, closed without merging