Fix crash on PUT /urls/<custom url> for long URLs
championswimmer/onepixel_backend pull request #58
Opened 2024-06-21 07:42 UTC by Praveen005

This change resolves #54 by adding validation checks before proceeding to create a specific shortcode URL.

Now if the shortcode is empty or its length exceeds 10 characters, it returns appropriate error and prevents panic.

2024-06-25 20:02 UTC, Praveen005 commented
Bhaiya @championswimmer, I need your feedback on this PR.

Do check whenever you find time.

2024-07-12 05:01 UTC, Praveen005 commented
Hi @championswimmer,

Just following up on this PR. Whenever you have a moment, could you please review it?

Regards.

2024-07-24 12:43 UTC, championswimmer requested changes

2024-07-24 12:43 UTC, championswimmer commented on .air.toml
> -root = "."
can we not generate changes in these files please?

2024-07-24 12:43 UTC, championswimmer commented on .github/workflows/build_test_release.yaml
> -name: Build, test and release
can we not generate changes in these files please?

2024-07-24 12:43 UTC, championswimmer commented on .gitignore
> -### JetBrains template
can we not generate changes in these files please?

2025-03-06 00:52 UTC, closed without merging